// utils/countryCodes.js

export const countryCodes = [
    { country: 'United States', code: '+1' },
    { country: 'United Kingdom', code: '+44' },
    { country: 'Canada', code: '+1' },
    { country: 'Australia', code: '+61' },
    { country: 'Germany', code: '+49' },
    { country: 'France', code: '+33' },
    { country: 'Italy', code: '+39' },
    { country: 'Spain', code: '+34' },
    { country: 'Netherlands', code: '+31' },
    { country: 'Belgium', code: '+32' },
    { country: 'Switzerland', code: '+41' },
    { country: 'Austria', code: '+43' },
    { country: 'Poland', code: '+48' },
    { country: 'Sweden', code: '+46' },
    { country: 'Norway', code: '+47' },
    { country: 'Denmark', code: '+45' },
    { country: 'Finland', code: '+358' },
    { country: 'Ireland', code: '+353' },
    { country: 'Portugal', code: '+351' },
    { country: 'Greece', code: '+30' },
    { country: 'Czech Republic', code: '+420' },
    { country: 'Hungary', code: '+36' },
    { country: 'Romania', code: '+40' },
    { country: 'Bulgaria', code: '+359' },
    { country: 'Croatia', code: '+385' },
    { country: 'Slovakia', code: '+421' },
    { country: 'Slovenia', code: '+386' },
    { country: 'Lithuania', code: '+370' },
    { country: 'Latvia', code: '+371' },
    { country: 'Estonia', code: '+372' },
    { country: 'Iceland', code: '+354' },
    { country: 'Luxembourg', code: '+352' },
    { country: 'Malta', code: '+356' },
    { country: 'Cyprus', code: '+357' },
    { country: 'Japan', code: '+81' },
    { country: 'South Korea', code: '+82' },
    { country: 'China', code: '+86' },
    { country: 'India', code: '+91' },
    { country: 'Singapore', code: '+65' },
    { country: 'Hong Kong', code: '+852' },
    { country: 'Taiwan', code: '+886' },
    { country: 'Thailand', code: '+66' },
    { country: 'Malaysia', code: '+60' },
    { country: 'Indonesia', code: '+62' },
    { country: 'Philippines', code: '+63' },
    { country: 'Vietnam', code: '+84' },
    { country: 'New Zealand', code: '+64' },
    { country: 'Brazil', code: '+55' },
    { country: 'Mexico', code: '+52' },
    { country: 'Argentina', code: '+54' },
    { country: 'Chile', code: '+56' },
    { country: 'Colombia', code: '+57' },
    { country: 'Peru', code: '+51' },
    { country: 'Venezuela', code: '+58' },
    { country: 'South Africa', code: '+27' },
    { country: 'Egypt', code: '+20' },
    { country: 'Nigeria', code: '+234' },
    { country: 'Kenya', code: '+254' },
    { country: 'Morocco', code: '+212' },
    { country: 'Turkey', code: '+90' },
    { country: 'Israel', code: '+972' },
    { country: 'UAE', code: '+971' },
    { country: 'Saudi Arabia', code: '+966' },
    { country: 'Russia', code: '+7' },
    { country: 'Ukraine', code: '+380' }
]